UPDATE products SET name = 'Берлінський експрес' WHERE id = 1;
UPDATE products SET name = 'Баварський денім' WHERE id = 2;
UPDATE products SET name = 'Сонячний імпульс' WHERE id = 3;
UPDATE products SET name = 'Неоновий лайм' WHERE id = 4;
UPDATE products SET name = 'Подих Сахари' WHERE id = 6;
UPDATE products SET name = 'Дух Торонто' WHERE id = 7;
UPDATE products SET name = 'Італійський кежуал' WHERE id = 8;
UPDATE products SET name = 'Геометрія стилю' WHERE id = 9;
UPDATE products SET name = 'Тропічний настрій' WHERE id = 10;
UPDATE products SET name = 'Альпійський сніг' WHERE id = 11;
UPDATE products SET name = 'Лазурний тенсел' WHERE id = 12;
UPDATE products SET name = 'Кришталеве озеро' WHERE id = 13;
UPDATE products SET name = 'Морський вовк' WHERE id = 14;
UPDATE products SET name = 'Глибина океану' WHERE id = 15;
UPDATE products SET name = 'Пульс міста' WHERE id = 16;
UPDATE products SET name = 'Lorenzoni Vesta' WHERE id = 17;
UPDATE products SET name = 'Флорентійський Акцент' WHERE id = 18;
UPDATE products SET name = 'Lorenzoni "Milano"' WHERE id = 19;
UPDATE products SET name = 'Impulso "Vector"' WHERE id = 20;
UPDATE products SET name = 'Ритм' WHERE id = 21;
UPDATE products SET name = 'Вуличний Імпульс' WHERE id = 22;
UPDATE products SET name = 'Milestone "Амбасадор"' WHERE id = 23;
UPDATE products SET name = 'Milestone "Virage"' WHERE id = 25;
UPDATE products SET name = 'Milestone "Tempo"' WHERE id = 26;
UPDATE products SET name = 'Кашемірова ніжність' WHERE id = 27;
UPDATE products SET name = 'Смарагдовий кашемір' WHERE id = 28;
UPDATE products SET name = 'Зимовий політ' WHERE id = 29;
UPDATE products SET name = 'Активний відпочинок' WHERE id = 30;
UPDATE products SET name = 'Нічний експрес' WHERE id = 31;
UPDATE products SET name = 'Зимовий марафон' WHERE id = 32;
UPDATE products SET name = 'Весняний трістан' WHERE id = 33;
UPDATE products SET name = 'Замшевий акцент' WHERE id = 34;
UPDATE products SET name = 'Легкий бриз' WHERE id = 35;
UPDATE products SET name = 'Весняний настрій' WHERE id = 36;
UPDATE products SET name = 'Італійський стиль' WHERE id = 37;
UPDATE products SET name = 'Літня прохолода' WHERE id = 38;
UPDATE products SET name = 'Венеціанський вечір' WHERE id = 39;
UPDATE products SET name = 'Пляжний сезон' WHERE id = 40;
UPDATE products SET name = 'Легка футболка Impulso' WHERE id = 41;
UPDATE products SET name = 'Бавовняний комфорт' WHERE id = 42;
UPDATE products SET name = 'Міський ритм' WHERE id = 44;
UPDATE products SET name = 'Класичне поло Impulso' WHERE id = 45;
UPDATE products SET name = 'Літній вечір' WHERE id = 46;
UPDATE products SET name = 'Твоя база' WHERE id = 47;
UPDATE products SET name = 'Простий вибір' WHERE id = 48;
UPDATE products SET name = 'Щоденний стиль' WHERE id = 49;
UPDATE products SET name = 'Універсальний солдат' WHERE id = 50;
UPDATE products SET name = 'Весняна куртка Milestone' WHERE id = 51;
UPDATE products SET name = 'Джинсові шорти Alberto' WHERE id = 52;
UPDATE products SET name = 'Футболка Montechiaro' WHERE id = 53;
UPDATE products SET name = 'Жилет Casa Moda' WHERE id = 54;
UPDATE products SET name = 'Кофта Casa Moda' WHERE id = 55;
UPDATE products SET name = 'Теплий трикотаж' WHERE id = 57;
UPDATE products SET name = 'Німецький жилет' WHERE id = 59;
UPDATE products SET name = 'Практичний вибір' WHERE id = 60;
UPDATE products SET name = 'Затишна кофта' WHERE id = 62;
UPDATE products SET name = 'Осінній вечір' WHERE id = 63;
UPDATE products SET name = 'Батник Casa Moda' WHERE id = 64;
UPDATE products SET name = 'Зимовий батник' WHERE id = 66;
UPDATE products SET name = 'Поло Casa Moda' WHERE id = 67;
UPDATE products SET name = 'Класична кофта' WHERE id = 70;
UPDATE products SET name = 'Німецький трикотаж' WHERE id = 73;
UPDATE products SET name = 'Офісний стиль' WHERE id = 77;
UPDATE products SET name = 'Діловий кежуал' WHERE id = 78;
UPDATE products SET name = 'Комфортна кофта' WHERE id = 81;
UPDATE products SET name = 'Спортивний батник' WHERE id = 83;
UPDATE products SET name = 'Завжди доречно' WHERE id = 84;
UPDATE products SET name = 'Твій комфорт' WHERE id = 85;
UPDATE products SET name = 'Прохолодний ранок' WHERE id = 86;
UPDATE products SET name = 'Активний день' WHERE id = 87;
UPDATE products SET name = 'Затишний вечір' WHERE id = 89;
UPDATE products SET name = 'Зимовий спорт' WHERE id = 90;
UPDATE products SET name = 'Спорт-шик Montechiaro' WHERE id = 91;
UPDATE products SET name = 'Мюнхенська ніч' WHERE id = 92;
UPDATE products SET name = 'Довга парка Milestone' WHERE id = 93;
UPDATE products SET name = 'Футболка Impulso' WHERE id = 95;
UPDATE products SET name = 'Річковий круїз' WHERE id = 96;
UPDATE products SET name = 'Смарагдовий лід' WHERE id = 98;
UPDATE products SET name = 'Зимова куртка Milestone' WHERE id = 99;
UPDATE products SET name = 'Ранковий вітер' WHERE id = 100;
UPDATE products SET name = 'Римські канікули' WHERE id = 101;
UPDATE products SET name = 'Лазурний берег' WHERE id = 102;
UPDATE products SET name = 'Блакитний горизонт' WHERE id = 103;
UPDATE products SET name = 'Шорти Impulso' WHERE id = 104;
UPDATE products SET name = 'Шорти Alberto' WHERE id = 105;
UPDATE products SET name = 'Брюки Alberto' WHERE id = 106;
UPDATE products SET name = 'Лляний бриз' WHERE id = 107;
UPDATE products SET name = 'Військовий льон' WHERE id = 108;
UPDATE products SET name = 'Чорний льон' WHERE id = 109;
UPDATE products SET name = 'Класичні брюки Alberto' WHERE id = 110;
UPDATE products SET name = 'Літні брюки Alberto' WHERE id = 111;
UPDATE products SET name = 'Джинсові шорти' WHERE id = 112;
UPDATE products SET name = 'Класичний денім' WHERE id = 113;
UPDATE products SET name = 'Денім тенсел' WHERE id = 114;
UPDATE products SET name = 'Літні шорти Alberto' WHERE id = 115;
UPDATE products SET name = 'Пляжний стиль' WHERE id = 116;
UPDATE products SET name = 'Преміум денім' WHERE id = 117;
UPDATE products SET name = 'Зимова парка Milestone' WHERE id = 118;
UPDATE products SET name = 'Парка кольору хакі' WHERE id = 119;
UPDATE products SET name = 'Шовковий дотик' WHERE id = 120;
UPDATE products SET name = 'Німецька парка' WHERE id = 121;
UPDATE products SET name = 'Бізнес денім' WHERE id = 122;
UPDATE products SET name = 'Футболка Casa Moda' WHERE id = 123;
UPDATE products SET name = 'Преміум слім денім' WHERE id = 124;
UPDATE products SET name = 'Кашеміровий блюз' WHERE id = 125;
UPDATE products SET name = 'Кашеміровий наві' WHERE id = 126;
UPDATE products SET name = 'Денім з кашеміром' WHERE id = 127;
UPDATE products SET name = 'Дорожній рух' WHERE id = 128;
UPDATE products SET name = 'Оксамитовий індиго' WHERE id = 129;
UPDATE products SET name = 'Чорний оксамит' WHERE id = 130;
UPDATE products SET name = 'Доріан Грей' WHERE id = 131;
UPDATE products SET name = 'Брюки Alberto' WHERE id = 133;
UPDATE products SET name = 'Сірий кандіані' WHERE id = 134;
UPDATE products SET name = 'Чорні чіноси' WHERE id = 137;
UPDATE products SET name = 'Класичні джинси Alberto' WHERE id = 138;
UPDATE products SET name = 'Преміум бізнес денім' WHERE id = 139;
UPDATE products SET name = 'Подвійний чорний' WHERE id = 140;
UPDATE products SET name = 'Шорти для відпочинку' WHERE id = 141;
UPDATE products SET name = 'Італійський спорт' WHERE id = 142;
UPDATE products SET name = 'Кофта Montechiaro' WHERE id = 143;